// AUTO-GENERATED by scripts/build-content.mjs — do not edit. Run `node scripts/build-content.mjs`.
import "server-only";

/**
 * Gated (commercial/academic/confidential) content bodies. SERVER-ONLY: the `server-only` import
 * above makes the build FAIL if any client component imports this module, so these bodies can never
 * reach the browser bundle. The /api/content gateway serves them per-request, post-entitlement-gate.
 */
export const CONTENT_BODIES: Record<string, string> = {};
