// GENERATED by scripts/gen-freshness.mjs (npm run docs:freshness). Do not edit by hand.
// Per-page audit freshness: how far each source repo has moved since the page's audited_against_sha.
export interface Freshness { repo: string; sha: string; head: string; behind: number | null; headDate: string }
export const FRESHNESS: Record<string, Freshness> = {
  "/aa/contracts": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/aa/guardians": {
    "repo": "citrate-identity",
    "sha": "9664fa8",
    "head": "9664fa8",
    "behind": 0,
    "headDate": "2026-09-06"
  },
  "/aa/identity": {
    "repo": "citrate-identity",
    "sha": "9664fa8",
    "head": "9664fa8",
    "behind": 0,
    "headDate": "2026-09-06"
  },
  "/aa/passkeys": {
    "repo": "citrate-sdk-js",
    "sha": "9d5959e",
    "head": "",
    "behind": null,
    "headDate": ""
  },
  "/aa/tutorials/sign-in-with-a-passkey": {
    "repo": "citrate-sdk-js",
    "sha": "bc5a830",
    "head": "2f8da46",
    "behind": 33,
    "headDate": "2026-09-07"
  },
  "/apps/boeing": {
    "repo": "citrate-boeing-shell",
    "sha": "efb6fec",
    "head": "efb6fec",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/buyer": {
    "repo": "citrate-buyer-webapp",
    "sha": "7d44b29",
    "head": "7d44b29",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/chatbot": {
    "repo": "citrate-chatbot",
    "sha": "e3827c3",
    "head": "e3827c3",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/comms": {
    "repo": "citrate-comms",
    "sha": "67557cf",
    "head": "67557cf",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/dashboard": {
    "repo": "citrate-dashboard",
    "sha": "727e62d",
    "head": "727e62d",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/district-registration": {
    "repo": "citrate-district-registration",
    "sha": "d907b0a",
    "head": "d907b0a",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/explorer": {
    "repo": "citrate-explorer",
    "sha": "6faab8a",
    "head": "6faab8a",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/landing": {
    "repo": "citrate-landing",
    "sha": "63adc44",
    "head": "63adc44",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/learning-center": {
    "repo": "citrate-learning-center",
    "sha": "a34f976",
    "head": "a34f976",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/memories": {
    "repo": "citrate-memories",
    "sha": "a616e75",
    "head": "a616e75",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/nist-agent": {
    "repo": "nist-agent",
    "sha": "4c1b12b",
    "head": "4c1b12b",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/studio": {
    "repo": "citrate-studio",
    "sha": "39cadf3",
    "head": "39cadf3",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/tutorials/explore-a-transaction": {
    "repo": "citrate-explorer",
    "sha": "6faab8a",
    "head": "6faab8a",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/tutorials/install-the-wallet-extension": {
    "repo": "citrate-wallet-extension",
    "sha": "930594c",
    "head": "930594c",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/apps/wallet-extension": {
    "repo": "citrate-wallet-extension",
    "sha": "930594c",
    "head": "930594c",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/addresses": {
    "repo": "citrate-chain",
    "sha": "c6e5906",
    "head": "9d5959e",
    "behind": 1,
    "headDate": "2026-09-07"
  },
  "/chain/bridge": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/cli": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/consensus": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/economics": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/genesis": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/lvm": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/network": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/precompiles-zkp": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/precompiles": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/rpc": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/sequencer": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/storage": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/tutorials/call-citrate-rpc": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/tutorials/deploy-a-contract-with-the-cli": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/chain/tutorials/read-the-dag": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/compute/agent-runtime": {
    "repo": "citrate-agent-runtime",
    "sha": "560c11a",
    "head": "f161e69",
    "behind": 46,
    "headDate": "2026-09-07"
  },
  "/compute/gateway": {
    "repo": "citrate-inference-gateway",
    "sha": "a2ad401",
    "head": "603fe92",
    "behind": 40,
    "headDate": "2026-09-07"
  },
  "/compute/node-agent": {
    "repo": "citrate-node-agent",
    "sha": "38bc9d1",
    "head": "0e63363",
    "behind": 20,
    "headDate": "2026-09-07"
  },
  "/compute/pool": {
    "repo": "citrate-compute-pool",
    "sha": "ae9358d",
    "head": "e5b7280",
    "behind": 57,
    "headDate": "2026-09-07"
  },
  "/contracts/compute": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/contracts/economics": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/contracts/edu": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/contracts/governance": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/contracts/models": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/contracts/reference": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/contracts/security": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/contracts/tutorials/interact-read-only": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/contracts/tutorials/read-a-contract": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/contracts/x402": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/core/for-agents": {
    "repo": "citrate-core",
    "sha": "2d88191",
    "head": "2d88191",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/core/getting-started": {
    "repo": "citrate-core",
    "sha": "2d88191",
    "head": "2d88191",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/core/overview": {
    "repo": "citrate-core",
    "sha": "2d88191",
    "head": "2d88191",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/core/run-a-node": {
    "repo": "citrate-core",
    "sha": "2d88191",
    "head": "2d88191",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/core/safety": {
    "repo": "citrate-core",
    "sha": "2d88191",
    "head": "2d88191",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/core/tour": {
    "repo": "citrate-core",
    "sha": "2d88191",
    "head": "2d88191",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/core/troubleshooting": {
    "repo": "citrate-core",
    "sha": "2d88191",
    "head": "2d88191",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/enterprise/compliance-full": {
    "repo": "citrate-compliance",
    "sha": "8757357",
    "head": "6cd442c",
    "behind": 8,
    "headDate": "2026-09-07"
  },
  "/enterprise/compliance": {
    "repo": "citrate-compliance",
    "sha": "8757357",
    "head": "6cd442c",
    "behind": 8,
    "headDate": "2026-09-07"
  },
  "/enterprise/dpa": {
    "repo": "citrate-compliance",
    "sha": "8757357",
    "head": "6cd442c",
    "behind": 8,
    "headDate": "2026-09-07"
  },
  "/enterprise/federal": {
    "repo": "citrate-compliance",
    "sha": "8757357",
    "head": "6cd442c",
    "behind": 8,
    "headDate": "2026-09-07"
  },
  "/enterprise/k12": {
    "repo": "citrate-docs",
    "sha": "8757357",
    "head": "",
    "behind": null,
    "headDate": ""
  },
  "/enterprise/procurement": {
    "repo": "citrate-commercial",
    "sha": "fea06db",
    "head": "d115816",
    "behind": 5,
    "headDate": "2026-09-07"
  },
  "/enterprise/questionnaires": {
    "repo": "citrate-compliance",
    "sha": "8757357",
    "head": "6cd442c",
    "behind": 8,
    "headDate": "2026-09-07"
  },
  "/operators/rewards": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/operators/run-a-node": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/operators/sell-compute": {
    "repo": "citrate-node-agent",
    "sha": "0e63363",
    "head": "0e63363",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/operators/tutorials/become-a-seller": {
    "repo": "citrate-node-agent",
    "sha": "0e63363",
    "head": "0e63363",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/research/atis": {
    "repo": "citrate-docs",
    "sha": "cd729ed",
    "head": "",
    "behind": null,
    "headDate": ""
  },
  "/research/bdd": {
    "repo": "citrate-chain",
    "sha": "03d7851",
    "head": "9d5959e",
    "behind": 477,
    "headDate": "2026-09-07"
  },
  "/research/gradient-papers": {
    "repo": "citrate-docs",
    "sha": "cd729ed",
    "head": "",
    "behind": null,
    "headDate": ""
  },
  "/research/learning": {
    "repo": "citrate-chain",
    "sha": "03d7851",
    "head": "9d5959e",
    "behind": 477,
    "headDate": "2026-09-07"
  },
  "/research/mentorship": {
    "repo": "citrate-docs",
    "sha": "03d7851",
    "head": "",
    "behind": null,
    "headDate": ""
  },
  "/research/paraconsistent": {
    "repo": "citrate-chain",
    "sha": "03d7851",
    "head": "9d5959e",
    "behind": 477,
    "headDate": "2026-09-07"
  },
  "/research/tla": {
    "repo": "citrate-agentile-archive",
    "sha": "4da2289",
    "head": "f28358f",
    "behind": 1,
    "headDate": "2026-07-16"
  },
  "/research/tutorials/reproduce-a-learning-round": {
    "repo": "citrate-chain",
    "sha": "03d7851",
    "head": "9d5959e",
    "behind": 477,
    "headDate": "2026-09-07"
  },
  "/research/verifiable-inference": {
    "repo": "citrate-chain",
    "sha": "03d7851",
    "head": "9d5959e",
    "behind": 477,
    "headDate": "2026-09-07"
  },
  "/sdks/bundler": {
    "repo": "citrate-bundler",
    "sha": "e1aa264",
    "head": "e1aa264",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/sdks/entitlements": {
    "repo": "citrate-sdk-js",
    "sha": "9664fa8",
    "head": "",
    "behind": null,
    "headDate": ""
  },
  "/sdks/identity": {
    "repo": "citrate-sdk-js",
    "sha": "9664fa8",
    "head": "",
    "behind": null,
    "headDate": ""
  },
  "/sdks/inference-gateway": {
    "repo": "citrate-inference-gateway",
    "sha": "603fe92",
    "head": "603fe92",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/sdks/js": {
    "repo": "citrate-sdk-js",
    "sha": "2f8da46",
    "head": "2f8da46",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/sdks/marketplace": {
    "repo": "citrate-sdk-marketplace",
    "sha": "5cc1f39",
    "head": "5cc1f39",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/sdks/python": {
    "repo": "citrate-sdk-python",
    "sha": "869694b",
    "head": "869694b",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/sdks/tutorials/first-app-with-sdk-js": {
    "repo": "citrate-sdk-js",
    "sha": "2f8da46",
    "head": "2f8da46",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/sdks/tutorials/post-a-marketplace-job": {
    "repo": "citrate-sdk-marketplace",
    "sha": "5cc1f39",
    "head": "5cc1f39",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/sdks/python/tutorials/python-quickstart": {
    "repo": "citrate-sdk-python",
    "sha": "869694b",
    "head": "869694b",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/start/primer": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  },
  "/start/roadmap": {
    "repo": "Citrate",
    "sha": "9d5959e",
    "head": "",
    "behind": null,
    "headDate": ""
  },
  "/start/tutorials/your-first-10-minutes": {
    "repo": "citrate-chain",
    "sha": "03d7851",
    "head": "9d5959e",
    "behind": 477,
    "headDate": "2026-09-07"
  },
  "/start/what-is-citrate": {
    "repo": "citrate-chain",
    "sha": "9d5959e",
    "head": "9d5959e",
    "behind": 0,
    "headDate": "2026-09-07"
  }
};
